server:
  port: 8081
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: sunweiqi123
  thymeleaf:
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qst.crm.po #起别名
logging:
  level:
    com.qst.crm.Dao: debug
devtools:
  restart:
   enabled: true
# 上传文件总的最大值
 # spring.servlet.multipart.max-request-size=10MB
  # 单个文件的最大值
 # spring.servlet.multipart.max-file-size=10MB


